export enum EUserRoleCognito {
  ROLE_GUEST = 'ROLE_GUEST',
  ROLE_SUPPLIER = 'NWRK_SUPPLIER',
  ROLE_CUSTOMER = 'NWRK_CUSTOMER',
  ROLE_ADMIN = 'NWRK_ADMIN',
  ROLE_PROPERTY_MANAGER = 'NWRK_PROPERTY_MANAGER',
  ROLE_CORPORATE_USER = 'CORPORATE_USER',
}
