import React from 'react';

import {
  Content,
  Section,
  Title,
  Paragraph,
  StyledParagraph,
  StyledOrderedList,
  StyledList,
  StyledUnorderedList,
} from '../../components/PolicyTypography';

const PrivacyPolicyContent = () => {
  return (
    <Content>
      <Section>
        <Title>SECTION I. INTRODUCTION</Title>
        <Paragraph>
          The privacy of our website users is of great importance to us, and we
          make every effort to ensure that it is protected. This policy explains
          how we use your personal information.
        </Paragraph>
        <Paragraph>
          By agreeing to the use of cookies during your first visit to our
          website, in accordance with the provisions of these Rules, you give us
          permission to use cookies during each of your subsequent visits.
        </Paragraph>
      </Section>
      <Section>
        <Title>SECTION II. COLLECTION OF PERSONAL DATA</Title>
        <StyledParagraph>
          The following types of personal data are subject to collection,
          storage and use:
        </StyledParagraph>
        <Paragraph>
          2.1. Information about your computer, including your IP address,
          geographic location, browser type and version, and operating system;
        </Paragraph>
        <Paragraph>
          2.2. Information about your visits to and use of this website,
          including referral sources, length of visits, pages viewed and site
          navigation paths;
        </Paragraph>
        <Paragraph>
          2.3. Information about your email address that you used to register on
          our website;
        </Paragraph>
        <Paragraph>
          2.4. Information you entered when creating a profile on our website,
          such as your name;
        </Paragraph>
        <Paragraph>
          2.5. Information, such as your name and email address, that you
          provided when you subscribed to our mailing lists and/or newsletters;
        </Paragraph>
        <Paragraph>
          2.6. Information that you entered when using the services of our
          website;
        </Paragraph>
        <Paragraph>
          2.7. Information generated by the use of our website, including
          information about the time, frequency and conditions of its use;
        </Paragraph>
        <Paragraph>
          2.8. Information that you have posted on our website for the purpose
          of publishing it on the Internet, including your username, profile
          picture and the content of your post;
        </Paragraph>
        <Paragraph>
          2.9 Information contained in any communications you have sent to us by
          email or through our website, including the content of the message and
          meta data;
        </Paragraph>
        <Paragraph>
          2.10 Any other personal information you have sent to us.
        </Paragraph>
        <Paragraph>
          Before you disclose personal information of a third party to us, you
          must obtain the consent of that person to both disclose and process
          that information in accordance with this policy.
        </Paragraph>
      </Section>
      <Section>
        <Title>SECTION III. USE OF YOUR PERSONAL INFORMATION</Title>
        <StyledParagraph>
          Personal information that you provide to us through our website will
          be used for the purposes specified in these rules or on the relevant
          pages of the website. We may use your personal information for the
          following purposes:
        </StyledParagraph>
        <Paragraph>3.1. Administering our website and business;</Paragraph>
        <Paragraph>3.2. Personalizing our website for you;</Paragraph>
        <Paragraph>
          3.3. Enabling you to use the services available on our website;
        </Paragraph>
        <Paragraph>
          3.4. Providing you with services purchased through our website;
        </Paragraph>
        <Paragraph>
          3.5. Sending you notices, invoices and payment reminders and receiving
          payments from you;
        </Paragraph>
        <Paragraph>
          3.6. Sending you non-marketing commercial communications;
        </Paragraph>
        <Paragraph>
          3.7. Sending you emails that you have specifically requested;
        </Paragraph>
        <Paragraph>
          3.8. Sending you email newsletters if you have requested them (you may
          notify us at any time that you no longer wish to receive email
          newsletters from us);
        </Paragraph>
        <Paragraph>
          3.9. Sending you marketing communications about our business
          activities or the business activities of carefully selected third
          parties that we believe may be of interest to you, either through
          publications or, if you have specifically consented to this, by
          sending you email or through the use of similar technologies (you may
          notify us at any time that you no longer wish to receive marketing
          communications);
        </Paragraph>
        <Paragraph>
          3.10. Providing third-party companies with statistical information
          about our users (however, these third-party companies will not be able
          to identify any individual user from this data);
        </Paragraph>
        <Paragraph>
          3.11. To process inquiries and complaints made by you or about you
          regarding our website;
        </Paragraph>
        <Paragraph>
          3.12. To ensure the security of our website and prevent fraud;
        </Paragraph>
        <Paragraph>
          3.13. To verify compliance with the terms and conditions governing the
          use of our website (including monitoring of private messages sent
          through the private messaging service of our website);
        </Paragraph>
        <Paragraph>3.14. For other purposes.</Paragraph>
        <StyledParagraph>
          If you have provided personal information for publication on our
          website, we will publish it. Otherwise, we will use this information
          in accordance with the license you have granted us.
        </StyledParagraph>
        <StyledParagraph>
          Your privacy settings can be used to limit the publication of your
          personal information on our website and can be adjusted through the
          privacy controls on the website.
        </StyledParagraph>
        <StyledParagraph>
          Without your express consent, we will not share your personal
          information with any third party company for direct marketing use by
          this or any other third party company.
        </StyledParagraph>
      </Section>

      <Section>
        <Title>SECTION IV. DISCLOSURE OF PERSONAL INFORMATION</Title>
        <StyledParagraph>
          We reserve the right to disclose your personal information to any of
          our employees, officers, policyholders, professional advisors, agents,
          suppliers or subcontractors to the extent and for the purposes set
          forth in these rules.
        </StyledParagraph>
        <Paragraph>
          4.1. In cases where we are required to do so by law;
        </Paragraph>
        <Paragraph>
          4.2. In connection with any current or future legal proceedings;
        </Paragraph>
        <Paragraph>
          4.3. In order to establish, exercise or defend our legal rights
          (including providing information to other parties for the purpose of
          preventing fraud or reducing credit risks);
        </Paragraph>
        <Paragraph>
          4.4. To a buyer (or prospective buyer) of any business or assets we
          sell (or intend to sell);
        </Paragraph>
        <Paragraph>
          to any person who we reasonably believe may request a court or other
          authorized body to disclose such personal data and, in our reasonable
          opinion, such court or authorized body will order the disclosure of
          such personal data.
        </Paragraph>
        <StyledParagraph>
          We will not disclose your personal information to third parties,
          except as specified in these rules.
        </StyledParagraph>
      </Section>

      <Section>
        <Title>
          SECTION V. INTERNATIONAL TRANSFERS OF PERSONAL INFORMATION
        </Title>
        <Paragraph>
          5.1. The information we collect may be stored, processed and
          transferred between any countries in which we operate in order to
          enable us to use this information in accordance with these rules.
        </Paragraph>
        <Paragraph>
          5.2. The information we collect may be transferred to the following
          countries that do not have data protection laws similar to those in
          force in the European Economic Area: USA, Russia, Japan, China and
          India.
        </Paragraph>
        <Paragraph>
          5.3. Personal information that you publish on our website, via the
          Internet, may be available worldwide. We cannot prevent its use or
          misuse for criminal purposes by unauthorized persons.
        </Paragraph>
        <Paragraph>
          5.4. By agreeing to these rules, you consent to the transfer of your
          personal information specified in SECTION V.
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION VI. STORAGE OF PERSONAL INFORMATION</Title>
        <Paragraph>
          6.1. Section VI sets out the Company's policies and procedures for the
          retention of personal information. These policies and procedures are
          designed to ensure that we comply with our legal obligations to retain
          and delete personal information.
        </Paragraph>
        <Paragraph>
          6.2. Personal information that we process for a specific purpose or
          purposes should not be stored for longer than necessary to achieve
          that purpose or those purposes.
        </Paragraph>
        <Paragraph>
          6.3. Without limiting the provisions set forth in clause 6.3.1, we
          generally delete personal information falling into the categories set
          forth below on the days and times set forth below:
        </Paragraph>
        <StyledOrderedList>
          <StyledList>
            Personal information will be deleted specify date and time;
          </StyledList>
          <StyledList>
            Not with standing the other provisions of Section E, we will retain
            documents (including electronic documents) that contain personal
            information where we are required to do so by law;
          </StyledList>
          <StyledList>
            In order to establish, exercise or defend our legal rights
            (including providing information to other parties to prevent fraud
            or reduce credit risks).
          </StyledList>
        </StyledOrderedList>
      </Section>

      <Section>
        <Title>SECTION VII. PROTECTION OF YOUR PERSONAL INFORMATION</Title>
        <Paragraph>
          7.1. We will take sufficient technical and organizational measures to
          prevent the loss, misuse or falsification of your personal
          information.
        </Paragraph>
        <Paragraph>
          7.2. We will store all personal information provided by you on our
          secure (both password and firewall) servers.
        </Paragraph>
        <Paragraph>
          7.3. You acknowledge that you are familiar with the fact that the
          transmission of information over the Internet is inherently
          unprotected, and we cannot guarantee the protection of data sent over
          the World Wide Web.
        </Paragraph>
        <Paragraph>
          7.4. You are solely responsible for keeping your password to access
          our website confidential. We will never ask for your password (except
          when you try to log in to your account on our website).
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION VIII. CHANGES AND AMENDMENTS</Title>
        <Paragraph>
          We reserve the right to make changes and amendments to these rules
          from time to time and to publish a new version on our website. You
          should periodically check this web page to make sure that you
          understand the content of the changes made to these rules. We may also
          inform you about changes to these rules by sending an e-mail or
          through the private messaging system of our website.
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION IX. YOUR RIGHTS</Title>
        <Paragraph>
          In practice, you will usually either consent in advance to our use of
          your personal information for marketing purposes or we will provide
          you with the opportunity to opt-out of our use of your information for
          marketing purposes.
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION X. THIRD PARTY WEBSITES</Title>
        <Paragraph>
          Our website contains hyperlinks to, and details about, third-party
          websites of third-party companies and individuals. We have no control
          over, and assume no responsibility for, the privacy policies and
          practices of such third party companies and individuals.
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION XI. UPDATING INFORMATION</Title>
        <Paragraph>
          Please notify us in a timely manner if your personal information held
          by us needs to be updated or corrected.
        </Paragraph>
      </Section>

      <Section>
        <Title>SECTION XII. COOKIES</Title>
        <Paragraph>
          Our website uses cookies. A cookie is a file containing an identifier
          (a string of letters and numbers) that is sent by a web server to a
          web browser and stored by the browser. Subsequently, the identifier is
          sent back to the server each time the browser requests a web page from
          the server. Cookies can be either "persistent" or "session" cookies:
          persistent cookies will be stored by the browser and will remain valid
          until the expiration date unless deleted by the user in advance;
          "session" cookies, on the contrary, will be deleted after the end of
          the session with the site or after the browser is closed. Cookies
          usually do not contain any information that identifies the user.
          However, your personal information that we hold may be linked to
          information stored and retrieved from cookies. (CHOOSE THE RIGHT
          PHRASE We use only session cookies/only persistent cookies/both
          persistent and session cookies on our website)
        </Paragraph>
        <Paragraph>
          The names of the cookies that we use on our website and the purposes
          for which they are used are listed below:
        </Paragraph>
        <Paragraph>
          On our website, we use Google Analytics and Adwords to recognize the
          computer, when a user (MARK ALL CASES WHERE COOKIES ARE USED ON THE
          SITE) visits the website / track user navigation on the website /
          allow the use of the user's shopping cart on the website / improve the
          usability of the website / analyze the use of the website / administer
          the website / prevent fraud and improve the security of the website /
          personalize the website for each user / target advertising that may be
          of interest to individual users / specify the purpose(s).
        </Paragraph>
        <Paragraph>
          Most browsers provide you with the opportunity to refuse the use of
          cookies, for example:
        </Paragraph>
        <StyledUnorderedList>
          <StyledList>
            In Internet Explorer (version 10) you can block using the cookie
            management settings available in the menu "Tools" - "Internet
            Options" - "Privacy" - "Advanced" ("Tools," "Internet Options,"
            "Privacy," "Advanced");
          </StyledList>
          <StyledList>
            In Firefox (version 24), you can block all cookies by clicking on
            "Tools" - "Options" - "Privacy": in the drop-down menu, select "Use
            custom log settings" and deselect "Accept cookies from websites";
            and finally;
          </StyledList>
          <StyledList>
            In Chrome (version 29), you can block all cookies by entering the
            "Settings and Management" menu, selecting "Settings" - "Show
            Advanced Settings" and "Content Settings", and then selecting
            "Prevent sites from sending any data" under the "Cookies" heading.
          </StyledList>
        </StyledUnorderedList>
        <StyledParagraph>
          Blocking all cookies will have a negative impact on the user
          experience of many websites. If you block cookies, you may not be able
          to use many features of our website.
        </StyledParagraph>
        <Paragraph>
          You can delete cookies that are already stored on your computer, for
          example:
        </Paragraph>
        <StyledUnorderedList>
          <StyledList>
            In Internet Explorer (version 10), you must delete cookies manually
            (instructions on how to do this can be found at
            http://support.microsoft.com/kb/278835);
          </StyledList>
          <StyledList>
            In Firefox (version 24), cookies can be deleted by going to the menu
            "Tools" - "Options" - "Privacy": in the drop-down menu, select "Use
            custom log settings", click "Show Cookies," and then "Delete all
            Cookies";
          </StyledList>
          <StyledList>
            In Chrome (version 29), you can delete all cookies by entering the
            "Settings and Management" menu, selecting "Settings" - "Show
            advanced settings" and "Clear browsing data", and then select
            "Delete cookies and other data and website plugins".
          </StyledList>
        </StyledUnorderedList>
        <Paragraph>
          Deleting cookies will have negative consequences for the usability of
          many websites.
        </Paragraph>
      </Section>
    </Content>
  );
};

export default PrivacyPolicyContent;
